# Этап сборки (build stage)
FROM node:16 AS build

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json (или yarn.lock, если используется yarn)
COPY client/package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем исходные файлы приложения в контейнер
COPY client/ ./

# Строим приложение
RUN npm run build

# Этап запуска (production stage)
FROM nginx:alpine

# Копируем собранные файлы из первого этапа в папку для статики nginx
COPY --from=build /app/build /usr/share/nginx/html

# Открываем порт 80 для nginx
EXPOSE 80

# Стартуем nginx
CMD ["nginx", "-g", "daemon off;"]
