# Используем официальный Go-образ для сборки
FROM golang:1.23 AS build

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем go.mod и go.sum для установки зависимостей
COPY go.mod go.sum ./

# Устанавливаем зависимости
RUN go mod tidy

# Устанавливаем утилиту migrate
RUN go install github.com/golang-migrate/migrate/v4/cmd/migrate@latest

# Копируем весь исходный код сервера
COPY ./ ./

# Собираем серверное приложение
RUN go build -o main ./cmd/app

# Этап с минимальным размером контейнера для финальной сборки
FROM golang:1.23-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем собранное приложение из этапа сборки
COPY --from=build /app/main /app/

# Копируем утилиту migrate в финальный контейнер
COPY --from=build /go/bin/migrate /usr/local/bin/

# Копируем миграции в контейнер
COPY ./migrations /migrations/

# Устанавливаем рабочий порт
EXPOSE 8000

# Запускаем миграции и сервер
CMD ["/bin/sh", "-c", "migrate -path=/migrations -database=$DATABASE_URL up && /app/main"]
